Rework pysmurf controller tests for sodetlib v0.5.0
simonsobs/socs pull request #378
Opened 2022-12-14 22:56 UTC by BrianJKoopman

## Description

This changes some of the tests to mock out the sodetlib functions a higher level. This is needed so that they don't depend on the sodetlib internals as much. Of course, if sodetlib function return values change significantly the mocked up values here will need updating.

### Questions
I had some questions that came up while working on this that'd be good to answer/incorporate here.

* What shape is `bsa.bgmap` typically? Here it's (12, 2), probably that's right, I just wanted to double check for myself.
* What's the `session.data` look like for `take_iv` on a live system?

## Motivation and Context

[Tests were failing](https://github.com/simonsobs/socs/actions/runs/3698000088/jobs/6263663111) on the update to sodetlib v0.5.0 being done following P10R1, in prep for P10R2. See https://github.com/simonsobs/socs/pull/376.

## How Has This Been Tested?

Tested locally with sodetlib v0.4.1 and v0.5.0. Tests were demonstrated to fail with v0.5.0 and pass in v0.4.1. Starting from v0.4.1 the tests were modified to change the mocks, creating the new mocked responses from the existing tests. Then tests were verified to pass with v0.5.0.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

2022-12-16 15:37 UTC, jlashner commented on tests/agents/test_pysmurf_controller_agent.py
the `bgmap` object in the BiasStepAnalysis is an array of len `nchans` with the i-th element being the bias group that readout-channel `i` belongs to, with -1 being unassigned. To test this we should probably do something like `np.zeros(1000)` and check that the 0-th bg has 1000 channels assigned to it.

2022-12-16 15:42 UTC, jlashner commented
Hey brian, going through and reviewing this now, but to answer the questions from the PR:
- The `bgmap` object is an array of length `nchans` with the i-th element being which bias line the i-th readout channel is assigned to (-1 being unassigned)
- The `take_iv` session data is currently set in the pysmurf-controller task (as opposed to through sodetlib), and is currently this:
  ```
      session.data = {
          'bands': iva.bands.tolist(),
          'channels': iva.channels.tolist(),
          'bgmap': iva.bgmap.tolist(),
          'R_n': iva.R_n.tolist(),
          'filepath': iva.filepath,
      }
  ```
where each of these lists has length `nchans`. We may want to consolidate this to create better summary statistics using quantiles if this is too much data, but for now it's been working fine.

2022-12-16 15:53 UTC, jlashner commented on tests/agents/test_pysmurf_controller_agent.py
> +    iva.filepath = 'test_file.npy'
`bands`, `channels`, and `bgmap` should all be arrays with length `nchans`. A self-consistent IV might have:

```
nchans = 100
bands = np.zeros(nchans)
channels = np.arange(nchans)
bgmap = np.zeros(nchans)
```

2022-12-16 15:54 UTC, jlashner commented on tests/agents/test_pysmurf_controller_agent.py
> +    assert session.data['R_n'] == [2, 2]
See comment above for what these should look like

2022-12-16 16:02 UTC, jlashner requested changes
Hey Brian, thanks for doing this!! It looks great, and I'm a lot more comfortable mocking functions at this level rather than the functions used internally to sodetlib. I added a few comments which I think clarify the structure of the sodetlib results, but this looks good to me.

2022-12-20 16:02 UTC, BrianJKoopman commented
Great, quick rebase, will merge momentarily.

2022-12-20 16:36 UTC, BrianJKoopman commented
Not sure why actions aren't re-running here. Going to just merge, they were passing before my rebase...

2022-12-20 16:37 UTC, merged