Adds an interface to  `bias_to_volt_arr`
simonsobs/socs pull request #396
Opened 2023-01-25 21:52 UTC by jlashner

Adds an interface to the `bias_to_volt_arr` sodetlib function.

## Description
During p10r2 testing we realized there is currently no task to allow you to directly set bias voltages. This can be accomplished using the `bias_to_volt_arr` function, which lets you set the `tes_bias_bipolar_array` for active bgs.
This adds an interface to use that function through the pysmurf-controller.

## How Has This Been Tested?
Not yet, but will test on the SAT

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] Unless I am preparing a release, I have opened this PR onto the `develop` branch.

2023-02-10 14:12 UTC, BrianJKoopman requested changes
This looks good to me! Just needs an example of the `session.data` in the docstring for the new task.

Once that's added I'm going to wait until you test it on the SAT before merging, so please let me know once that's done.

2023-02-10 14:12 UTC, BrianJKoopman commented on socs/agents/pysmurf_controller/agent.py
> +            session.data['biases'] = biases.tolist()
Add `session.data` example to docstring.

2024-09-24 22:17 UTC, BrianJKoopman commented
@jlashner another to check in on. Still needed?

2024-09-30 17:57 UTC, jlashner commented
I think this may still be useful, however with the pysmurf-controller restructure to running things in sub-processes, I think this would require some work. I am fine closing this until it comes up again.

2024-09-30 17:57 UTC, closed without merging