Updates to ibootbar Agent
simonsobs/socs pull request #446
Opened 2023-05-22 20:58 UTC by davidvng

## Description

Various updates to the ibootbar agent. Includes logic change to handling connection drops, which is the same with UPS agent. Created new task `lock_outlet` that can lock/unlock a specified outlet. If an outlet is locked, other tasks such as `set_outlet` will fail. Currently initializing the agent with all outlets unlocked, but can change this in the future to take in a config file.

## Motivation and Context

Resolves #417, resolves #437.

## How Has This Been Tested?

Tested on ibootbar at Yale.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2023-05-23 06:33 UTC, mhasself commented
I see this is a draft, but two immediate reactions:
- I think the presence of locked outlets need not prevent a "reboot".  In most cases, outlets will be set to reboot into their current state.
- It is essential that we can lock outlets on agent startup.  Either a config file or simply "--lock-outlet 1 --lock-outlet 3 --lock-outlet 8" or something like that.

Thanks!

2023-05-24 20:45 UTC, mhasself requested changes
Thank you!  I think there's still an issue with propagating session.data in some failure modes, see comment.

2023-05-24 20:45 UTC, mhasself commented on socs/agents/ibootbar/agent.py
> +        raise TypeError('Unable to interpret SNMP response.')
The oid_cache is not returned if you raise an error.  So there's no point in setting it inside this "except" clause.

You need to decide whether you'll report errors by raising exceptions, or through the return value.

2023-05-30 17:59 UTC, BrianJKoopman requested changes
Awesome, just a couple small suggestions from me.

2023-05-30 17:59 UTC, BrianJKoopman commented on tests/integration/test_ibootbar_agent_integration.py
Great to see added tests! You could also add a locked outlet to the config file so that it's locked at Agent startup, which would test lines 191-195, as well as toggle the lock off, which would test lines 440-441.

2023-06-01 13:24 UTC, mhasself requested changes
Thanks for these changes!

A few simple notes inline.  Also:  I see you have hard-coded the number 60, representing the sampling loop period in seconds, in a bunch of different places.  This is also used to modify lastGet, to trigger updates.  That "60" should become a constant declared at the top of the program.
-

2023-06-02 00:32 UTC, mhasself commented
Sorry, one more thing while you're in there -- can you add the "locked" information to acq's session.data?  This will help to make the display in ocs-web more informative.  E.g.
```
        "outletStatus_0": {"status": 1,                                                                        
                           "name": Outlet-1,
                           "locked": False,                                                                   
                           "description": "on"}
```

2023-06-05 18:21 UTC, davidvng commented on socs/agents/ibootbar/agent.py
>      @ocs_agent.param('cycle_time', default=10, type=int)
The MIB file states that the OID for setting cycle time is type Integer32. I've tried setting it to float, and the ibootbar seems to automatically round to the nearest int and still cycle the outlet, however the task itself crashes due to type error.

2023-06-05 18:58 UTC, mhasself commented on socs/agents/ibootbar/agent.py
> +        self.sample_rate = 60
Meaning of "period" vs "rate" is important for clarity.  Please change to sample_period.

2023-06-05 18:59 UTC, mhasself commented on socs/agents/ibootbar/agent.py
>      @ocs_agent.param('cycle_time', default=10, type=int)
Ah, ok.  Thanks for re-checking.  Int it is then!

2023-06-05 19:01 UTC, mhasself approved these changes
Thanks for those fixes.  I'm very happy with this now, except the rate -> period terminology issue where noted.

2023-06-05 20:25 UTC, BrianJKoopman requested changes
The only thing from me is the testing changes we discussed in person @davidvng. To summarize those:

* Re-add test for "set state on".
* Test cycle task locks out when outlet locked.
* Make sure test names represent what they're testing (i.e. `test_ibootbar_lock_outlet` currently is more of a test of a unlocking an outlet.)

2023-06-06 19:54 UTC, merged