Adds general task to set TES biases
simonsobs/socs pull request #545
Opened 2023-10-11 13:23 UTC by jlashner

Adds a general task to set tes biases to specified values, and a separate task to zero biases. Resolves #544.

## Description

Adds a needed function to the pysmurf-controller `set_biases` that lets you generally set tes biases. Also adds `zero_biases` task which can makes it easier to zero all biases from OCS web.

## Motivation and Context

We need more control over TES biases from pysmurf-controller.

## How Has This Been Tested?

Not tested yet.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [X] I have updated the documentation accordingly.

2023-10-29 17:17 UTC, kmharrington commented
We could really use these functions running in the field. What's needed to get it going there?

2023-10-30 14:23 UTC, BrianJKoopman requested changes
Looks good, mostly docstring related requests.

2023-11-07 13:20 UTC, jlashner commented on socs/agents/pysmurf_controller/agent.py
> +    @ocs_agent.param('bias')
decided that bias shouldn't be optional for this func, but forgot to change the docstring.

2023-11-07 13:20 UTC, jlashner commented
sorry that took so long, but addressed @BrianJKoopman's feedback

2023-11-07 16:57 UTC, BrianJKoopman approved these changes
Thanks for the updates!

2023-11-07 16:57 UTC, merged