Add stimulator encoder agent / driver.
simonsobs/socs pull request #612
Opened 2024-01-09 06:27 UTC by dixilo

## Description

This pull request adds reader for stimulator encoder.
This agent run in Kria KR260 inside the stimulator electronics box.
This reader accesses a custom-made IP inside the PL of ZynqMP device.
The firmware code can be found in https://github.com/dixilo/kr260_stm.
## Motivation and Context

These codes will be used to read encoder of the stimulator to know exact rotation speed and timing of the signal chopping.

## How Has This Been Tested?

We tested the functionality using the stimulator in Princeton.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2025-01-28 20:14 UTC, davidvng requested changes
Thanks for the PR! Looks good overall, I added some comments for consistency similar to my previous PRs.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/agent.py
> +    _ = parser.add_argument_group('Agent Options')
Add `--path-dev` and `--path-lock` as arguments here.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/drivers.py
Change the prefix of class names from `Stm`- to `Stim`-.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/agent.py
> +            session.data = {"fields": {}}
Can drop `"fields"` here.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/agent.py
> +                if len(ts_list) != 0:
Add a log to `self.log` if this condition is not satisfied.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/agent.py
> +                time.sleep(0.01)
Use the `Pacemaker`.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/agent.py
> +                    data['timestamps'] = ts_list
This should go into `data['data']['timestamps']`.

2025-01-28 20:14 UTC, davidvng commented on socs/agents/stm_encoder/agent.py
> +                data = {'timestamps': [], 'block_name': 'stm_enc', 'data': {}}
Change to standard timestamp key in the data dictionary, then move the list of timestamps into data (see below).
```suggestion
                current_time = time.time()
                data = {'timestamp': current_time, 'block_name': 'stm_enc', 'data': {}}
```

2025-01-29 15:44 UTC, BrianJKoopman reviewed
A couple of small additional comments.

2025-01-29 15:44 UTC, BrianJKoopman commented on socs/agents/stm_encoder/agent.py
> +        '''
Follow the process docstring formatting recommendations here:
```suggestion
        '''acq()
        
        **Process** - Start acquiring data.
        '''
```
Also add `session.data` structure to the docstring.

2025-01-29 15:44 UTC, BrianJKoopman commented on socs/agents/stm_encoder/drivers.py
> +PATH_LOCK = Path(__file__).parent.joinpath('.lock')
This puts the lock file in where the socs module is installed, which isn't necessarily writable. This should be moved somewhere else. I would suggest `/tmp/`.

2025-01-29 18:21 UTC, mhasself commented
Great to see this an apologies if these two concerns are premature:
- What's the data rate?  If very fast, then you need separate feeds for aggregator / influx.
- I don't think it's acceptable to have the UTC - TAI offset hard-coded to 37.  Either explicitly store TAI, or have a way of getting utc-tai dynamically (including regular updates), or have an assertion, on start-up, that the current time is before Jan 1 2026.

2025-02-05 10:05 UTC, dixilo commented on socs/agents/stm_encoder/agent.py
> +                if len(ts_list) != 0:
Encoder data will not appear if the stimulator chopper is not rotating.
Becasue we will rotate the chopper only during calibration, this condition is not satisfied during usual observation.
So I think adding a log for this condition will make too much information

2025-02-05 10:30 UTC, dixilo commented
Thanks for the review!

> * What's the data rate?  If very fast, then you need separate feeds for aggregator / influx.
Data rate is around 250 Hz when rotated at the maximum speed.
The encoder will send data only during calibration time.
For the current calibration plan, data rate ~30 Hz to ~250 Hz continues for about 2 minutes during time constant calibration.

Do we need separate feeds for aggregator / influx for this situation?

2025-02-05 10:59 UTC, dixilo commented
> I don't think it's acceptable to have the UTC - TAI offset hard-coded to 37. Either explicitly store TAI, or have a way of getting utc-tai dynamically (including regular updates), or have an assertion, on start-up, that the current time is before Jan 1 2026.

Thanks for the comment. I'm planning to implement the routine to get utc-tai dynamically.

2025-02-06 06:33 UTC, dixilo commented
> I don't think it's acceptable to have the UTC - TAI offset hard-coded to 37. Either explicitly store TAI, or have a way of getting utc-tai dynamically (including regular updates), or have an assertion, on start-up, that the current time is before Jan 1 2026.

I decided not to include UTC - TAI conversion and provide raw TAI values since it is difficult to implement the behavior at the leap second insertion.

2025-02-19 18:10 UTC, BrianJKoopman requested changes
The changes mostly look good to me, except for the format for the message published to the high rate feed. See the comment below.

2025-02-19 18:10 UTC, BrianJKoopman commented on socs/agents/stimulator_encoder/agent.py
> +                        downsample_time = current_time
Sorry, I think there's some confusion about the format for publishing to data feeds and for `session.data`.

For each `publish_to_feed` call, the format for the `message` argument needs to be either:
```
message = {
    'block_name': <Key to identify group of co-sampled data>
    'timestamp': <ctime of data>
    'data': {
        'field_name_1': <datapoint1>,
        'field_name_2': <datapoint2>
    }
}
```

if your fields are singular data points, or:
```
message = {
    'block_name': <Key to identify group of co-sampled data>
    'timestamps': [ctime1, ctime2, ... ]
    'data': {
        'field_name_1': [data1_1, data1_2, ...],
        'field_name_2': [data2_1, data2_2, ...]
    }
}
```

if you're publishing a list of points for each field. So 'timestamp' becomes 'timestamps' and is a list.

For the high rate data, as written currently, it looks like the format is:
```
message = {
    'block_name': 'stim_enc',
    'timestamp': current_time
    'data': {
        'timestamps_tai': [data1_1, data1_2, ...],
        'state': [data2_1, data2_2, ...]
    }
}
```

This might cause an issue in the HK aggregator. @mhasself any thoughts on the timestamps published being in TAI here?

2025-02-19 18:19 UTC, BrianJKoopman commented on socs/agents/stm_encoder/agent.py
> +                    data['timestamps'] = ts_list
This makes sense for the `session.data` object, but since `data` is being used in the `self.agent.publish_to_feed()` call 'timestamps' needs to be at this higher level. See https://ocs.readthedocs.io/en/main/developer/feeds.html#recorded-feed-message-format.

2025-02-19 18:20 UTC, BrianJKoopman commented on socs/agents/stm_encoder/agent.py
> +                data = {'timestamps': [], 'block_name': 'stm_enc', 'data': {}}
Related to above, plural 'timestamps' is important for the publish to feed call, and when publishing a list of points, needs to also contain a list for the associated value.

2025-02-20 14:18 UTC, mhasself commented on socs/agents/stimulator_encoder/agent.py
> +                        downsample_time = current_time
Putting the timestamps into a data field called `timestamps_tai` is a good solution.

As @BrianJKoopman says, you need to also record a full vector of timestamps, in message['timestamps'].  The most appropriate thing would be to grab the system time using `time.time()` in the `while not self._dev.fifo.empty()` loop.  (Those timestamps are not high precision but they're still useful and relevant... e.g. you can use them to make a very good guess of the [UTC - TAI] offset in processing, later.)

2025-02-20 14:41 UTC, mhasself commented on socs/agents/stimulator_encoder/agent.py
> +                        downsample_time = current_time
I have two more general comments on the data feeds here.

In the "slow" feed, for grafana, it will not be that useful to have a heavily downsampled version of the raw data.  I would be *much more interested* for a regular published value of the spin frequency, computed from the last ~2 seconds of data.  Instead of 10 Hz, just do 0.5 Hz and do a pulse count / time delta.

Furthermore -- for that slow feed, it's useful to publish the frequency *even when the thing isn't spinning*.  That is helpful to distinguish between "there were no encoder pulses" and "the agent/process wasn't running".

If the slow feed has spin frequency, and is always running ... then I want it in the Aggregator / permanent HK data too!

So ya -- I think you should just record the fast data to aggregator, and then record a slower feed with spin frequency, including when freq=0, for both influx + aggregator.

(In the slow feed, instead of timestamps_tai you could record the most recent value of (timestamp_tai - timestamp) -- that will hover around the current UTC offset (37 or something).)

2025-02-21 02:24 UTC, dixilo commented on socs/agents/stimulator_encoder/agent.py
> +                    en_st_list.append(_d.state)
Thank you for pointing out. We don't need 100 Hz here at all.

FIFO depth inside the FPGA firmware is 512 and the loop [here](https://github.com/simonsobs/socs/blob/a9c5c319c51696cd59e0f4d98ab2e4c11bc883b3/socs/agents/stimulator_encoder/drivers.py#L212) is taking it into account.
Since the fifo accessed from the agent is a Queue object on Python and the device has 4GB DDR4 memory, 1 Hz reading perfectly works.

I will simply reduce the loop time to 0.5 Hz so that we don't need to care about the different loop time between fast and slow feeds.

2025-02-21 15:52 UTC, mhasself commented on socs/agents/stimulator_encoder/agent.py
> +                    en_st_list.append(_d.state)
Those changes look great to me!

2025-02-27 16:38 UTC, BrianJKoopman approved these changes
Thanks for all the updates on this one! Looks good to me, going to go ahead and merge.

2025-02-27 16:39 UTC, merged