Oriental Motor BLH controller agent for stimulator
simonsobs/socs pull request #690
Opened 2024-06-11 09:18 UTC by dixilo

## Description

This pull request adds a new agent to operate motor to be used in the stimulator for LAT.
The motor cotroller is Orienta Motor's BLH series with USB controll capability.
This agent communicate with the controller to start or stop rotation and change parameter settings such as rotation speed.

## Motivation and Context

Since the BLH series motor controller will be used in the LAT stimulator,
the agent should be contained in this repository.

## How Has This Been Tested?

Test was done using an actual motor controller and an ARM-based single board computer.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2025-01-24 19:38 UTC, davidvng requested changes
Thank you for the PR! This looks great overall. Many of my comments will be similar/identical to @BrianJKoopman's review of #694.

Since this agent is using a direct serial connection, and you've tested using a single board computer, I imagine this will not be run on the `daq-lat` node as most other agents. Other cases where this occurs would be the LS240s, whose agents are usually run on a NUC that either has direct USB connection or USB-to-fiber adapters. What is the plan for this agent?

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +        '''
Move up to class docstring.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +        '''
Please standardize the naming and docstrings according to https://ocs.readthedocs.io/en/main/developer/agent_references/documentation.html#task-and-process-documentation.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +        sleep_time = 1 / f_sample - 0.1
Use the Pacemaker here.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +            session.set_status('running')
This should be removed.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +            session.data = {"fields": {}}
Can drop `"fields"` here.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +    def stop_acq(self, session, params=None):
Change to `_stop_acq`.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +    def set_values(self, session, params=None):
Add `@ocs_agent.param` decorator here.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/om_comm.py
Add a brief description of what this file contains.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +                field_dict = {'motor': {'RPM': speed}}
This could be a flatter structure by removing `'motor'`.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +                self._blh.set_accl_time(decl_time, accl=False)
You should be able to remove the conditionals after including the param decorators.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +    def start_rotation(self, session, params=None):
Similar to other tasks, you can add a param decorator here.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +        return True, 'BLH rotation started.'
You should handle the case where the start command failed to run properly, thus the return statement that the rotation started would be incorrect. See my comment in `drivers.py`.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/drivers.py
> +        self._wr(MOVE_FWD if forward else MOVE_BKW)
If this returns something, you should return it at the end of this function too. This could then be handled in the agent to see whether the command worked as intended.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/drivers.py
> +        self._wr(STOP)
Same comment as for `start`.

2025-01-24 19:38 UTC, davidvng commented on socs/agents/orientalmotor_blh/agent.py
> +        return True, 'BLH rotation stop command was published.'
Same comment as in `start_rotation`.

2025-01-27 01:41 UTC, dixilo commented
Thanks for the review!
This device will be directly connected to a single-board computer inside the electronics box of the stimulator via USB.

2025-01-27 01:47 UTC, dixilo commented on docs/agents/orientalmotor_blh.rst
> +
The single board computer we are planning to use is ARM based, which is not compatible with the `socs` docker image.
Because of this problem, we will use the agent directly (without docker) in the single-board computer, and this is the reason why it doesn't have the docker compose section in the document.

2025-01-27 02:28 UTC, dixilo commented on socs/agents/orientalmotor_blh/agent.py
> +                self._blh.set_accl_time(decl_time, accl=False)
I added param decorators.
Conditionals here are still needed since it is controlling wheter it configures the parameter according to the value is specified or not (default to None).

2025-01-27 22:05 UTC, BrianJKoopman reviewed
One small comment/question on the documentation, otherwise looks good. Thanks!

2025-01-29 07:57 UTC, dixilo commented on docs/agents/orientalmotor_blh.rst
Driver installation is not needed for this device.
I added the information on the device file to the documentation.

2025-01-29 16:05 UTC, BrianJKoopman approved these changes

2025-01-29 16:06 UTC, merged