hwp-supervisor: make  IBootState compatible with synaccess.
simonsobs/socs pull request #693
Opened 2024-06-11 22:43 UTC by ykyohei

Make IBootState compatible with synaccess agent originally it was only compatible with ibootbar agent.

## Description
Make IBootState compatible with synaccess agent and add encoder timestamp
This PR addresses https://github.com/simonsobs/socs/issues/691 and https://github.com/simonsobs/socs/issues/681

## Motivation and Context
https://github.com/simonsobs/socs/issues/691 and https://github.com/simonsobs/socs/issues/681

## How Has This Been Tested?
Tested in daq-dev for satp3

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-06-12 07:33 UTC, jlashner requested changes
Hi Kyohei, this seems good to me! I have a few requests inline. Do we know why this is suddenly not working for SATp3? As far as I know, nothing in the configuration has changed recently.

2024-06-12 07:33 UTC, jlashner commented on socs/agents/hwp_supervisor/agent.py
> +    driver_power_agent_type: Literal['iboot, synaccess']
Can we change this to just `agent_type`? The `driver-power-agent-type` arg is for specifying the power-agent type of the HWP driver board, so in the IBootState class we don't need those first two descriptors.

2024-06-12 07:33 UTC, jlashner commented on socs/agents/hwp_supervisor/agent.py
> +                                            args.driver_power_agent_type)
Here we'll need a new command-line arg `args.gripper_power_agent_type` which is not necessarily the same as the driver power type.

2024-06-12 14:42 UTC, ykyohei commented
Right, the configuration is not changed, and I'm confused why it was working before. HWP agents skips IBootState monitoring if synaccess agent is down when HWP agent is brought up, so we might have been in such an edge case. But I couldn't completely reproduce the previous state.

2024-06-16 01:47 UTC, jlashner approved these changes
Thanks for the changes!

2024-06-19 03:10 UTC, merged