Add devantech dS378 ethernet relay agent
simonsobs/socs pull request #694
Opened 2024-06-14 02:07 UTC by dixilo

## Description

This pull request adds a new agent to operate devantech's dS378 ethernet relay.

## Motivation and Context

Since dS378 is used in the electronics of the stimulator, the agent should be included in this repository.

## How Has This Been Tested?

Test was done using the actual dS378 device.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2024-12-17 22:10 UTC, BrianJKoopman commented on socs/agents/devantech_dS378/drivers.py
One recent thing we've been trying to do in our agents is make them robust to network outages. We're tracking that effort in https://github.com/simonsobs/socs/issues/721, and there's a related discussion in https://github.com/simonsobs/socs/discussions/538.

In short, we'd like to be able for the agent to automatically reconnect to the device its communicating with. For devices like this one that rely on a TCP connection I recently added [this TCPInterface class](https://github.com/simonsobs/socs/blob/7631d0ecb9fe836434277bb677b91fd937fa85c9/socs/tcp.py#L5). It handles things like `TimeoutError` and other connection related exceptions, and will raise a `ConnectionError`, which the agent can then catch and react to accordingly by reconnecting to the device.

Again, this is relatively new, but is important for the long running processes. The only real example of this at the moment is the [CryomechAgent drivers](https://github.com/simonsobs/socs/blob/main/socs/agents/cryomech_cpa/drivers.py). I'm okay with putting this off to another PR (and adding this Agent to that issue I linked to), but I just wanted to mention it.

2025-01-09 05:49 UTC, dixilo commented on docs/agents/devantech_dS378.rst
> +see documentation provided from the manufacturer).
I added the link to the Manufacturer's documentation.

2025-01-09 05:50 UTC, dixilo commented on docs/agents/devantech_dS378.rst
I added autodoc of the `dS378` class in `drivers.py`

2025-01-09 05:51 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +IP_DEFAULT = '192.168.215.241'
I see. I removed the hard-coded default IP from the codes.

2025-01-09 05:52 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +class dS378Agent:
Thanks, I modified the class name to `DS378Agent`. Driver class is also renamed to `DS378` according to the same rule.

2025-01-09 05:52 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +
Thanks, I moved the docstring.

2025-01-09 05:53 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +    def __init__(self, agent, ip=IP_DEFAULT, port=17123):
Yes, ip is now a required argument.

2025-01-09 05:55 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +        '''
Thanks for this comment. I followed the instruction for `acq`, `set_relay`, `get_relays` functions to address this comment.

2025-01-09 05:56 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +        """
I added underscore to this function.

2025-01-09 05:57 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +    def set_relay(self, session, params=None):
Thanks, now `set_relay` checks arguments with the decorator.

2025-01-09 05:58 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +            See document
I added a description for this argument rather than just saying "See documents".

2025-01-09 05:58 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +        sleep_time = 1 / f_sample - 0.1
Thanks, I used the Pacemaker. Please let me know if the usage was wrong.

2025-01-09 05:59 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +            session.set_status('running')
`session.set_status('running')` was removed

2025-01-09 05:59 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
> +                                pulse_time=params['pulse_time'])
Yes, now `set_relay` has decorators to address this issue.

2025-01-09 06:00 UTC, dixilo commented on socs/agents/devantech_dS378/agent.py
I didn't know that, Thanks. I changed single quotes to double quotes.

2025-01-09 06:00 UTC, dixilo commented on socs/agents/devantech_dS378/drivers.py
> +    ds_dev = dS378('192.168.215.100', 17123)
Yes, I removed hard coded IP address.

2025-01-09 06:13 UTC, dixilo commented on socs/agents/devantech_dS378/drivers.py
Thanks for the work!
I modified my driver and agent code to use `TCPInterface` class.

During debugging, I noticed that communication after reconnection causes crash due to unmatched length of returned message.
This might be due to unsent message in the previous connection buffered somewhere is sent after reconnection though my program assumes the unsent message was aborted and there would be no reply.

To address this problem, I also added a code to check the length of the data (and flush/discard if it doesn't match) to the `drivers.py`.

2025-01-09 06:24 UTC, dixilo commented
Thanks for your detailed review!
I modified the codes according to your review comments.

2025-01-10 21:35 UTC, BrianJKoopman requested changes
This looks great, thanks for addressing all the comments, and for your detailed responses! A few more small suggestions.

It's great to see use of the `TCPInterface` class too, glad that was straightforward. Just to confirm, the agent now can gracefully recover itself from a network interruption, say if you disconnected the network cable to the dS378?

I'm going to push a couple of small changes as well that I figured would just be quicker to do while I was re-reviewing. Please be sure to pull those before continuing with the suggested changes. Thanks again!

2025-01-10 21:35 UTC, BrianJKoopman commented on socs/agents/devantech_dS378/drivers.py
> +        raise ConnectionError
This looks like the code [that you mentioned](https://github.com/simonsobs/socs/pull/694#discussion_r1908217838) is handling dropping partial responses when reconnecting. Do you mind just adding a comment here describing what problem this is solving. (The `TCPInterface` class also tries twice before giving up, so without some context this might look a little strange to someone looking at this down the road.)

2025-01-20 09:17 UTC, dixilo commented
Thanks for the review and the comments!
I modified the codes according to your suggestions.

2025-01-22 20:53 UTC, BrianJKoopman approved these changes
Thanks for implementing the suggestions, looks great!

2025-01-22 20:53 UTC, merged