Adding stimulator thermometer agent.
simonsobs/socs pull request #695
Opened 2024-06-17 05:00 UTC by dixilo

## Description

This is a PR to add stimulator thermometer agent.

## Motivation and Context

The stimulator is equiped with original thermometer readout based on MAX31856 and MAX31865.
This agent add functionality to read these devices via Industrial I/O subsystem equipped in Linux kernel.

## How Has This Been Tested?

The functionality was tested using the actual MAX31856 and MAX31865 devices.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.

2025-01-27 17:04 UTC, davidvng requested changes
Thank you for the PR! This looks good overall, just some comments for consistency that are similar to my previous review.

Also double checking that this agent will also run on a dedicated computer that connects to these devices via USB, like the `BLHAgent`?

2025-01-27 17:04 UTC, davidvng commented on socs/agents/stm_thermo/agent.py
> +    devices = [from_spi_node_path(path) for path in args.paths_spinode]
You should move this into the agent itself, so that you can handle error cases within the agent.

2025-01-27 17:07 UTC, davidvng commented on socs/agents/stm_thermo/agent.py
> +class StmThermometerAgent:
Forgot to add to my review: could you change to `StimThermometerAgent` and change elsewhere when needed?

2025-01-27 22:11 UTC, BrianJKoopman reviewed
A few small comments in addition to @davidvng's.

2025-01-27 22:11 UTC, BrianJKoopman commented on docs/agents/stm_thermo.rst
> +ocs-config
Small consistency nitpick:
```suggestion
OCS Site Config
```

2025-01-27 22:11 UTC, BrianJKoopman commented on socs/agents/stm_thermo/agent.py
> +    pgroup.add_argument('--paths_spinode', nargs='*', type=str, required=True,
Change to `--paths-spinode` to follow convention for CLI arguments.
```suggestion
    pgroup.add_argument('--paths-spinode', nargs='*', type=str, required=True,
```

2025-01-27 22:11 UTC, BrianJKoopman commented on docs/agents/stm_thermo.rst
> +        'arguments': [['--paths_spinode', [
Change for consistency below.

```suggestion
        'arguments': [['--paths-spinode', [
```

2025-02-06 08:30 UTC, dixilo commented
> Also double checking that this agent will also run on a dedicated computer that connects to these devices via USB, like the BLHAgent?

It runs on a dedicated computer (KR260) like BLHAgent.
KR260 has GPIO pins like Raspberry Pis and it will use these pins to read the devices (MAX31856/MAX31865) via SPI protocol (not via USB connection).

2025-02-18 22:01 UTC, BrianJKoopman requested changes
Thanks for the updates, two small changes needed. And I had one additional question. Otherwise looks good to go!

2025-02-18 22:01 UTC, BrianJKoopman commented on socs/plugin.py
> +    'StmThermometerAgent': {'module': 'socs.agents.stm_thermo.agent', 'entry_point': 'main'},
Needs updating for the new Agent class name and module path.

```suggestion
    'StimThermometerAgent': {'module': 'socs.agents.stimulator_thermometer.agent', 'entry_point': 'main'},
```

2025-02-20 07:09 UTC, dixilo commented on socs/agents/stimulator_thermometer/agent.py
> +                        field_dict = {chan_string: {'T': temp, 'T_cj': cjtemp}}
`_cj` means 'cold junction'.
Themocouple measures temperature difference between cold junction and measurement junction.
Cold junction temperature is measured inside the chip (MAX31856) and used to obtain absolute value of the measurement junction temperature.
Although it will not be directly used in the stimulator analysis, it may help diagnosis of the stimulator's health.

2025-02-20 15:11 UTC, BrianJKoopman approved these changes
Looks good, thanks for all the updates!

2025-02-20 15:12 UTC, merged