Bug fix of wiregrid_actuator/Dockerfile for Ubuntu update
simonsobs/socs pull request #759
Opened 2024-09-26 09:57 UTC by sadachi5

## Description

The `socs/docker/wiregrid_actuator/Dockerfile` was changed in this PR to make it compatible with the Ubuntu 22.

## Motivation and Context

The previous wiregrid_actuator/Dockerfile was incompatible with the recent OCS version, which is based on Ubuntu 22,  because the installation method for the actuator controller libraries (`gclib`, `gcapsd`) was changed from Ubuntu 20.

## How Has This Been Tested?

The connection test to the actuator controller has been done at Kyoto.

## Types of changes

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-09-26 20:50 UTC, BrianJKoopman requested changes
Thanks for the update and for testing! Two small suggestions to reduce the warnings during build.

2024-09-26 20:50 UTC, BrianJKoopman commented on docker/wiregrid_actuator/Dockerfile
> + && python3 setup.py install \
I know it's in the upstream instructions, but direct invocation of `setup.py` like this is deprecated. Can we change this line to `python3 -m pip install . \` instead?

I was able to build successfully using this.

Previous build:
```
/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: SetuptoolsDeprecationWa
rning: setup.py install is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` directly.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html for details.
        ********************************************************************************

!!
  self.initialize_options()
/opt/venv/lib/python3.10/site-packages/setuptools/_distutils/cmd.py:66: EasyInstallDeprecationW
arning: easy_install command is deprecated.
!!

        ********************************************************************************
        Please avoid running ``setup.py`` and ``easy_install``.
        Instead, use pypa/build, pypa/installer or other
        standards-based tools.

        See https://github.com/pypa/setuptools/issues/917 for details.
        ********************************************************************************

!!
  self.initialize_options()
ERROR setuptools_scm._file_finders.git listing git files failed - pretending there aren't any
zip_safe flag not set; analyzing archive contents...
gclib location: /home/ocs/gclib.py
```

New build:
```
Processing /home/ocs
  Preparing metadata (setup.py): started
  Preparing metadata (setup.py): finished with status 'done'
Building wheels for collected packages: gclib
  Building wheel for gclib (setup.py): started
  Building wheel for gclib (setup.py): finished with status 'done'
  Created wheel for gclib: filename=gclib-1.0-py3-none-any.whl size=5509 sha256=a5dd87761922a01
d76cf616ca1e2440c5f2f8d6ac9ffddaacc0ca0f68082bc6e
  Stored in directory: /tmp/pip-ephem-wheel-cache-mo6q0wb9/wheels/4a/c9/f4/70900c0ce2d621b50abb
09a7fa008c78c8e367e7453fd3a63c
Successfully built gclib
Installing collected packages: gclib
Successfully installed gclib-1.0
gclib location: /home/ocs/gclib.py
```

2024-09-26 20:50 UTC, BrianJKoopman commented on docker/wiregrid_actuator/Dockerfile
This warning comes up a couple times during the build:
```
debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (This frontend requires a controlling tty.)
debconf: falling back to frontend: Teletype
dpkg-preconfigure: unable to re-open stdin:
```

It can be mitigated by adding `ENV DEBIAN_FRONTEND="noninteractive"` before the `RUN` command on line 5, before or after `WORKDIR /home/ocs/`.

2024-09-26 22:26 UTC, sadachi5 commented
@BrianJKoopman  I updated the Dockerfile as you suggested. Please check it.

2024-09-27 02:42 UTC, BrianJKoopman approved these changes
Looks good, thanks!

2024-09-27 02:43 UTC, merged