Debug the wiregrid_tiltsensor agent
simonsobs/socs pull request #764
Opened 2024-09-29 11:37 UTC by d-hoshino2626

## Description

I changed the wiregrid_tiltsensor agent and moxa_serial.py in the socs/common directory.
In the wiregrid_tiltsensor, I removed the type of argument from `add_argument` and added cast of the port.
In the moxa_serial.py, I added new argument, `device=kikusui`, to the class `Serial_TCPServer`. This argument is for recognize which device the serial-to-LAN converter communicate with. The tilt sensor needs to send commands not decoded and recieve commands not encoded. This change detect the device to communicate and judge the neccesity of encoding and decoding of commands.
## Motivation and Context

To debug the wiregrid_tiltsensor agent.
## How Has This Been Tested?

Tested in my lab, using a serial-to-LAN converter.
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2024-10-01 14:01 UTC, BrianJKoopman requested changes
Great, thanks for working on this! A couple small comments to address below.

2024-10-07 05:37 UTC, d-hoshino2626 commented on socs/agents/wiregrid_tiltsensor/agent.py
> -    pgroup.add_argument('--ip-address', dest='ip', type=str, default=None,
In commit https://github.com/simonsobs/socs/pull/764/commits/178b764475b2c90e43081e2102d24de57a5c1753, I re-added the type=str. When I was debugging this issue, I misunderstood that this is one of the causes and removed it.

2024-10-07 05:38 UTC, d-hoshino2626 commented on socs/common/moxa_serial.py
> +    def __init__(self, port, timeout=MOXA_DEFAULT_TIMEOUT, device="kikusui"):
In commit https://github.com/simonsobs/socs/pull/764/commits/de81b2f2c8a6303e2b9e6b5c1cbf1be4448d455d, 
I changed device='kikusui' to encoded=True and added docstrings.

2024-10-07 05:39 UTC, d-hoshino2626 commented
Thanks, Brian!
I changed according to your comment and checked this change working well in our lab.

2024-10-07 16:13 UTC, BrianJKoopman approved these changes
> Thanks, Brian! I changed according to your comment and checked this change working well in our lab.

Looks great, thanks for the updates!

2024-10-07 16:14 UTC, merged