Adds flags for ACU checking to hwp supervisor, along with tests
simonsobs/socs pull request #802
Opened 2024-12-16 13:34 UTC by jlashner

## Description

## Motivation and Context
This adds gripper-state monitoring to the HWP `monitor` process, and adds the following flags to the HWP state which can be checked by the ACU:
- `gripper_state` which can be "cold", "warm", "ungripped", or "unknown"
- `is_spinning` boolean

## How Has This Been Tested?
Along with these changes, I am building out the HWP emulator into a set of integration tests that test the behavior of these flags and other operations. We would also like to test with the ACU on hardware.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [X] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [X] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

2025-01-03 00:48 UTC, jlashner commented
@BrianJKoopman Ended up getting the tests to work properly! Turns out I missed a shutdown call for one of the device_emulators in the hwp emulator. Adding that makes tests clean up correctly, so I reverted the misc changes I made to test the github workflow.

This contains the same update to the HWP supervisor as https://github.com/simonsobs/socs/pull/805, so if you'd rather just review and merge this one we can close the other one. Thanks!

2025-01-07 21:22 UTC, BrianJKoopman requested changes
This is great, awesome to see all the tests come together for the supervisor agent. Mostly small documentation related comments. The `SIGKILL` workaround for getting the tests to run does mean code coverage doesn't get reported, which is unfortunate. It's makes it a bit challenging to understand what really gets tested.

2025-01-16 17:56 UTC, jlashner commented
Hey Brian, this is now passing tests, having fixed issues with shutting down some agents with SIGINT, and is ready for another review. Thanks!

2025-01-16 22:30 UTC, BrianJKoopman reviewed
Thanks, this fixes the issue with `SIGKILL` in the supervisor tests, but the problem still remains in the PID agent tests when I run locally. Coverage goes from 0% to 95% on the agent if I change the `SIGKILL` on this line to a `SIGINT`:
https://github.com/simonsobs/socs/blob/8ebb61e94cf3144431b4e426f277ac6ab4c83b73/tests/integration/test_hwp_pid_agent_integration.py#L36

Tests results running locally with that line sending `SIGKILL` vs sending `SIGINT`:
```
$ python3 -m pytest --cov --cov-report term integration/test_hwp_pid_agent_integration.py
================================================================ test session starts ================================================================
platform linux -- Python 3.11.9, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/koopman/git/socs/tests
configfile: pytest.ini
plugins: order-1.3.0, dependency-0.6.0, cov-6.0.0, docker-3.1.1, twisted-1.14.3, anyio-4.4.0
collected 8 items

integration/test_hwp_pid_agent_integration.py ........                                                                                         [100%]

---------- coverage: platform linux, python 3.11.9-final-0 -----------
Name                                                                             Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------
/home/koopman/git/socs/socs/agents/hwp_pid/agent.py                                210    210     0%
/home/koopman/git/socs/socs/agents/hwp_pid/drivers/pid_controller.py               267    219    18%

$ python3 -m pytest --cov --cov-report term integration/test_hwp_pid_agent_integration.py
================================================================ test session starts ================================================================
platform linux -- Python 3.11.9, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/koopman/git/socs/tests
configfile: pytest.ini
plugins: order-1.3.0, dependency-0.6.0, cov-6.0.0, docker-3.1.1, twisted-1.14.3, anyio-4.4.0
collected 8 items

integration/test_hwp_pid_agent_integration.py ........                                                                                         [100%]

---------- coverage: platform linux, python 3.11.9-final-0 -----------
Name                                                                             Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------
/home/koopman/git/socs/socs/agents/hwp_pid/agent.py                                210     11    95%
/home/koopman/git/socs/socs/agents/hwp_pid/drivers/pid_controller.py               267     69    74%
```

Is this `SIGKILL` required in the CI? Tests run fine on my system without it. Or is there a similar solution that would remove the need to send `SIGKILL` in those tests?

Also, please address or comment on the other comments I made in the last review.

2025-01-17 18:37 UTC, jlashner commented
Right, thanks for the reminder. I went through and addressed your previous comments, if you want to take another look!

2025-01-17 19:42 UTC, BrianJKoopman approved these changes
Looks great, thanks for working through all the difficulties with the tests!

2025-01-17 19:42 UTC, merged